name: Linux ARM (Docker)

on:
  pull_request:
    types: [synchronize, opened]
  push:
    branches:
      - main

env:
  DEBIAN_FRONTEND: noninteractive
  SCRCPY_VERSION: 1.24

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.2.0

      - uses: docker/setup-buildx-action@v1
        with:
          install: true

      - uses: docker/setup-qemu-action@v1
          
      - name: Build with Docker
        run: |
          # Override Scrcpy version in Dockerfile
          docker build \
            -t scrcpy-linux-arm:latest \
            --output=type=docker \
            --platform=linux/arm64 \
            --build-arg SCRCPY_VERSION \
            ./docker
      - name: Extract build files from Docker instance
        run: |
          docker create -ti --name scrcpy-linux-arm-tmp scrcpy-linux-arm bash
          docker cp scrcpy-linux-arm-tmp:/scrcpy/x/app/scrcpy .

      - uses: actions/upload-artifact@v2
        with:
          name: artifacts_linux_arm_lib
          path: scrcpy
          